// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paqlcflzhjpgvlgcfrfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcWxjZmx6aGpwZ3ZsZ2NmcmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzAxNTcsImV4cCI6MjA1ODk0NjE1N30.vY9srLDEWl7DlS9afRxiPJ7WJ-AZFWlK-C4dqt-M2T0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);